### PR TITLE
When requesting /{db}/{docid}?rev=X and X doesn't exist 404 should be returned

### PR DESCRIPTION
**Pull request by jeqq**
This is working fo GET requests, not for DELETE requests (in the documentation: http://docs.couchdb.org/en/latest/api/document/common.html#delete--db-docid the rev parameter can be also used with DELETE requests). We need to patch the core to make this to work.

### CODE REVIEW

**Comment by dickolsson** [comment]
I will merge the attachment endpoint soon (#6). This PR might have to be rebased after I do that, because there might be a few small conflicts.

**Comment by dickolsson** [comment]
@jeqq Can you explain why we need to patch core to make this work for DELETE requests?

**Comment by jeqq** [comment]
With the actual implementation we are not able to add query parameters to the url:

```
case 'DELETE':
        $curl_options = array(
          CURLOPT_HTTPGET => FALSE,
          CURLOPT_CUSTOMREQUEST => 'DELETE',
          CURLOPT_URL => _url($url, array('absolute' => TRUE)),
          CURLOPT_NOBODY => FALSE,
          CURLOPT_HTTPHEADER => array('X-CSRF-Token: ' . $token),
        );
        break;
```

**Comment by dickolsson** [comment]
@jeqq We have overidden the method from core. See `\Drupal\relaxed\Tests\ResourceTestBase::httpRequest()`. This means that we should be able to do any modifications we need to make this work. Or am I missing something?

**Comment by dickolsson** [comment]
Did you rebase this branch? It looks like other changes are included as well?

**Comment by jeqq** [comment]
Yes, I rebased it.

**Comment by dickolsson** [comment]
@jeqq Something must have gone wrong while you rebased the branch. It doesn't look right, see [the file diff](https://github.com/dickolsson/drupal-relaxed/pull/8/files). I can also see that some commits seems to be appearing twice in the log... So something is not right in this branch.

Can you please extract your changes and maybe create a new clean branch from `8.x-1.x`?

**Comment by jeqq** [comment]
@dickolsson I've created a new branch and a PR: https://github.com/dickolsson/drupal-relaxed/pull/9

**Pull request closed without merging**
