### PR TITLE
Enabling PHP 7 in Travis config, but allowing failures still.

### PR DESCRIPTION
**Pull request by dickolsson**

### CODE REVIEW

**Comment by dickolsson** [comment]
I've got a new Travis setup that I made for key_value and multiversion, with a better PHP-FPM setup and Nginx. I think I'll merge that instead of this PR.

**Comment by dickolsson** [comment]
I haven't pushed it yet though, will do later today.

**Comment by jeqq** [comment]
@dickolsson Ok, I just wanted to see if tests are passing with PHP 7.

**Comment by dickolsson** [comment]
Seems like they do! :+1: :smile:

**Comment by dickolsson** [comment]
Closing as this is dealt with in #48.

**Pull request closed without merging**
